### ISSUE TITLE
Navigation Bar - Admin Page

### ISSUE THREAD

**Issue by ianc125** [Tenma-Server/Tenma#39]
A way to get to the admin page in the navigation bar.
A way to get back to the homepage from the admin side.

**Comment by hmhrex** [comment]
I'm actually planning on writing a new interface that will make the django admin side of things irrelevant. Right now I'm just using it to tweak and test, but my hope is to phase it out in favor of integrating into the front-end.

I'm closing this only because there's another strategy to do something similar in the works. Thanks for all the feedback @ianc125! It's nice to have someone speak their mind. I can work with that. 😊
