### ISSUE TITLE
Series with same names being merged on accident.

### ISSUE THREAD

**Issue by ianc125** [Tenma-Server/Tenma#43]
Example

Take The Following Series:

- Planet of the Apes (1974)
29 Issues
- Planet of the Apes (2011)
16 Issues

Instead of having 2 separate series loaded in the DB it is merging everything under Planet of the Apes (1974) and showing duplicates for issues 1 through 16 because there is 16 issues in the 2011 series.
Each duplicate issue below goes to each raw file from each separate series though. It just looks like its all form the 1974 series on the UI side.

![duplicate issues](https://user-images.githubusercontent.com/25814126/29805191-148519b8-8c56-11e7-87f4-668a43403430.PNG)

**Comment by ianc125** [comment]
I cleaned this up by going through each issue that was incorrect and manually setting the Comicvine ID. More interested as to why it couldn't find the correct series in first place though.

**Comment by hmhrex** [comment]
This is due to the matching method. It's still a WIP and has been evolving quite a bit. I did a test with a little over 1000 files, and I was at about 71% correct matching. Still needs a lot of tuning. unfortunately Comic Vine doesn't make this easy with the way they organize some of their data. I'm going to close this as this feature is in heavy ongoing development.
