### ISSUE TITLE
no issue really

### ISSUE THREAD

**Issue by tarnecki** [Tenma-Server/Tenma#60]
hi mate,
where can we discuss your project? if we have questions for example: very long cache / and matching wrong comics from vine etc?

appreciate a link of something to any boards when i can ask questions? thanks

**Comment by hmhrex** [comment]
The project is not dead, however it is on hiatus. I’ve unfortunately had to put it aside due to family matters over the last 8 months. I am hoping to pick it back up again at some point soon.

As a consumer of FOSS software, I know this can be frustrating, but please understand, as the sole maintainer it can be very difficult to continue traction when it is a side-project.

To answer your original question: GitHub is currently where we communicate about Tenma. If you have a specific question, you are welcome to search through the issues, or create one yourself.

I’ll close this comment since it answers your original question, but feel free to open another issue if you have any other questions!
